// export tag aliases
export Brand from '@tags/Brand/Brand';
export Button from '@tags/Button/Button';
export Heading from '@tags/Heading/Heading';
export Icon from '@tags/Icon/Icon';
export Image from '@tags/Image/Image';
export Link from '@tags/Link/Link';
export List from '@tags/List/List';
export Media from '@tags/Media/Media';
export PlaceholderSvg from '@tags/PlaceholderSvg/PlaceholderSvg';
export Rhythm from '@tags/Rhythm/Rhythm';
export RichText from '@tags/RichText/RichText';
export Wrapper from '@tags/Wrapper/Wrapper';
